version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3003:3003"
    volumes:
      - ./app/newproject:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"
    environment:
      - DB_HOST=db
      - DB_NAME=app-db
      - DB_USER=app-user
      - DB_PASS=app-password
    depends_on:
      - db
  db:
      image: postgres:13-alpine
      environment:
        - POSTGRES_DB=app-db
        - POSTGRES_USER=app-user
        - POSTGRES_PASSWORD=app-password
      ports:
        - "5432:5432"
      volumes:
        - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume:
